
CREATE USER ACCOUNTING IDENTIFIED BY ACCOUNTING;

DROP TABLE ACCOUNTING.ACCOUNTS_OWNERS;
DROP TABLE TRADING.TRADES;
DROP TABLE ACCOUNTING.ACCOUNTS;

CREATE TABLE ACCOUNTING.ACCOUNTS
(
    ACCOUNT_ID VARCHAR2(10) NOT NULL,
    ACCOUNT_NAME VARCHAR2(20) NOT NULL UNIQUE,
    ACCOUNT_DESCRIPTION VARCHAR2(40),
    CREATE_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
    CURRENCY VARCHAR2(3) NOT NULL,
    CURRENCY_AMOUNT FLOAT DEFAULT 0.0 NOT NULL,
    
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
);

DROP TABLE ACCOUNTING.ACCOUNTS_OWNERS;

CREATE TABLE ACCOUNTING.ACCOUNTS_OWNERS
(
    ACCOUNT_ID VARCHAR2(10) NOT NULL UNIQUE,
    OWNER_NAME VARCHAR2(20) NOT NULL,
    OWNER_COUNTRY_RESIDENCE VARCHAR2(2) NOT NULL,
    BIRTH_DATE TIMESTAMP NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
    
    CONSTRAINT ACCOUNTS_OWNERS_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTING.ACCOUNTS (ACCOUNT_ID)
);


CREATE USER TRADING IDENTIFIED BY TRADING;

GRANT REFERENCES ON ACCOUNTING.ACCOUNTS TO TRADING;

DROP TABLE TRADING.TRADES;

CREATE TABLE TRADING.TRADES
(   
    TRADE_ID INT NOT NULL,
    ACCOUNT_ID VARCHAR2(10) NOT NULL,
    TRADE_TYPE VARCHAR2(10) NOT NULL,
    TRADE_AMOUNT FLOAT NOT NULL,
    TRADE_CURRENCY VARCHAR2(3) NOT NULL,
    EFFECTIVE_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
    
    CONSTRAINT TRADES_PK PRIMARY KEY (TRADE_ID),
    CONSTRAINT TRADES_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTING.ACCOUNTS (ACCOUNT_ID)
);

DROP TABLE TRADING.EXCHANGE_RATES;

CREATE TABLE TRADING.EXCHANGE_RATES
(   
    FROM_CURRENCY VARCHAR2(3) NOT NULL,
    TO_CURRENCY VARCHAR2(3) NOT NULL,
    RATE FLOAT NOT NULL,
    EFFECTIVE_DATE TIMESTAMP DEFAULT SYSDATE,
    UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
    
    CONSTRAINT EXCHANGE_RATES_UN UNIQUE (FROM_CURRENCY, TO_CURRENCY, EFFECTIVE_DATE)
);

commit;

